Algoritmo "Introdução a - Repita-ate"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Algoritmo de introdução a estrutura condicional "Repita - Ate "
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 08/09/2021
Var
   cont : Inteiro


Inicio
   cont <- 0
   Repita
   Escreval (cont)
   cont<-cont+1
   Ate cont>5  // verdadeiro até que se torne falso.


Fimalgoritmo