Algoritmo "Exercicio A"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Apresentar os resultados de uma tabuada de multiplicar (de 1 até 10) de um número qualquer.
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 03/09/2021
Var
num, i: Inteiro


Inicio
 Escreval ("Escolha um número: ")
 Leia (num)
 Enquanto i <= 10 faca
 Escreval ( i , " *", num, " =", i*num)
 i<-i+1
 FimEnquanto



Fimalgoritmo