Algoritmo "Laço de Repetição"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos 
// Descrição   : Como criar um algoritmo de repetição "Enquanto/faca"
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 03/09/2021
Var
 cont : Inteiro


Inicio
     Enquanto cont<10 faca
     Escreval ("Osasco")
     cont<-cont+1
     FimEnquanto


Fimalgoritmo