Algoritmo "Exercicio 2"
// Disciplina   : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Algoritmo que mostra o sucessor ao digitado.
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 25/08/2021
Var
   numero, sucessor: real


Inicio
   Escreval ("ALGORITMO SUCESSOR")
   Escreva ("Escolha um número: ")
   Leia (numero)
   sucessor<-numero+1
   Escreval ("O sucessor ao número escolhido é: ", sucessor)

Fimalgoritmo