Algoritmo "Decremento-Para"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Demonstração de decremendo dentro da estrutura PARA
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 09/09/2021
Var
   cont, cont1 : Inteiro
   resp : Real

Inicio
   Para cont de 50 ate 1 passo -1 faca
      Escreval (cont)
   FimPara

Fimalgoritmo