Algoritmo "Exemplo 2-Para"
// Disciplina  : [Lógica de Programação e JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Introdução a estrutura de repetição PARA
// Autor(a)    : Vinicius de Souza Cestari
// Data atual  : 09/09/2021
Var
   cont, acum : Inteiro
   resp : Real

Inicio
   Para cont de 50 ate 70 passo 2 faca
      Escreval (cont)
      acum<-acum+cont
   FimPara
      resp<-acum/11
      Escreval ("A média será de: ", resp)

Fimalgoritmo